const QUESTIONS = window.QUIZ_QUESTIONS || [];
const SETS = {
  laptop: {name:"Video 1 — Laptop Hardware", short:"Video 1", filter:q=>q.video==="laptop"},
  motherboard: {name:"Video 2 — Motherboards/Mainboard", short:"Video 2", filter:q=>q.video==="motherboard"},
  connections: {name:"Video 3 — Motherboard Connections", short:"Video 3", filter:q=>q.video==="connections"},
  cpu_features: {name:"Video 4 — CPU Features", short:"Video 4", filter:q=>q.video==="cpu_features"},
  all: {name:"Tất cả video", short:"Tất cả", filter:q=>true}
};
const state={activeSet:"laptop", sourceSet:"laptop", order:[], current:0, answers:{}, showQuestionVi:true, showOptionVi:true, showVocab:true, showExplain:true, isRetry:false, theme:localStorage.getItem("aPlusTheme")||"light"};
document.documentElement.dataset.theme=state.theme;
const $=id=>document.getElementById(id);
function baseOrder(setId=state.activeSet){return QUESTIONS.map((q,i)=>SETS[setId].filter(q)?i:null).filter(i=>i!==null)}
function setOrder(setId, clear=false){state.activeSet=setId;state.sourceSet=setId;state.order=baseOrder(setId);state.current=0;state.isRetry=false;if(clear) clearAnswersForOrder(state.order);$("setSelect").value=setId;showQuiz();render();}
function clearAnswersForOrder(order){order.forEach(i=>delete state.answers[i])}
function q(){return QUESTIONS[state.order[state.current]]} function qIndex(){return state.order[state.current]}
function answeredCount(){return state.order.filter(i=>state.answers[i]).length} function correctCount(){return state.order.filter(i=>state.answers[i]===QUESTIONS[i].answer).length} function wrongCount(){return answeredCount()-correctCount()}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function updateMetrics(){const total=state.order.length, ans=answeredCount();$("mAnswered").textContent=`${ans}/${total}`;$("mScore").textContent=correctCount();$("mWrong").textContent=wrongCount();$("mSet").textContent=state.isRetry?"Câu sai":SETS[state.activeSet].short;$("progressFill").style.width=total?`${ans/total*100}%`:"0%"}
function renderToggles(){[["toggleQuestionVi","showQuestionVi"],["toggleOptionVi","showOptionVi"],["toggleVocab","showVocab"],["toggleExplain","showExplain"]].forEach(([id,k])=>{$(id).classList.toggle("active",state[k]);$(id).querySelector("span").textContent=state[k]?"ON":"OFF"})}
function renderMap(){const box=$("questionMap");box.innerHTML="";state.order.forEach((idx,pos)=>{const b=document.createElement("button");b.textContent=pos+1;if(pos===state.current)b.classList.add("current");if(state.answers[idx])b.classList.add(state.answers[idx]===QUESTIONS[idx].answer?"correct":"wrong");b.title=QUESTIONS[idx].title;b.onclick=()=>{state.current=pos;showQuiz();render()};box.appendChild(b)})}
function renderGlossary(){let terms=[];state.order.forEach(i=>QUESTIONS[i].keywords.forEach(k=>terms.push(k)));terms=[...new Set(terms)].sort((a,b)=>a.localeCompare(b,"vi"));const query=$("glossarySearch").value.trim().toLowerCase();if(query)terms=terms.filter(t=>t.toLowerCase().includes(query));else terms=terms.slice(0,28);$("glossaryList").innerHTML=terms.map(t=>`<div class="term">${t}</div>`).join("")}
function renderQuestion(){const item=q(), idx=qIndex(), selected=state.answers[idx];$("topic").textContent=`${SETS[state.activeSet].name} · Câu ${state.current+1}/${state.order.length}`;$("statusPill").textContent=selected?`Bạn chọn ${selected} · Đáp án ${item.answer}`:"Chưa trả lời";$("statusPill").style.color=selected?(selected===item.answer?"var(--green)":"var(--red)"):"var(--muted)";$("questionText").textContent=item.question_en;$("questionVi").textContent=item.question_vi;$("questionVi").style.display=state.showQuestionVi?"block":"none";const ans=$("answers");ans.classList.toggle("showVi",state.showOptionVi);ans.innerHTML="";item.options.forEach(o=>{const b=document.createElement("button");b.className="ans";b.disabled=!!selected;if(selected){if(o.key===item.answer)b.classList.add("correct");if(o.key===selected&&selected!==item.answer)b.classList.add("wrong")}b.innerHTML=`<div class="letter">${o.key}</div><div><strong>${o.en}</strong><span>${o.vi}</span></div><div class="mark">${o.key===item.answer?"Đúng":"Sai"}</div>`;b.onclick=()=>{state.answers[idx]=o.key;toast(o.key===item.answer?"Chính xác." : `Sai. Đáp án đúng là ${item.answer}.`);render();if(answeredCount()===state.order.length)setTimeout(showResults,700)};ans.appendChild(b)});$("vocabBox").style.display=state.showVocab?"block":"none";$("keywordChips").innerHTML=item.keywords.map(k=>`<span class="chip">${k}</span>`).join("");$("explainBox").style.display=(state.showExplain||selected)?"block":"none";$("explainText").innerHTML=selected?`<strong style="color:${selected===item.answer?"var(--green)":"var(--red)"}">${selected===item.answer?"Bạn chọn đúng.":"Bạn chọn sai."}</strong><br>Đáp án đúng: <strong>${item.answer}</strong><br>${item.explain}`:item.explain;$("prevBtn").disabled=state.current===0;$("nextBtn").textContent=state.current===state.order.length-1?"Xem kết quả →":"Câu sau →"}
function renderBanner(){$("retryBanner").style.display=state.isRetry?"block":"none";$("retryText").textContent=state.isRetry?`Bạn đang luyện lại ${state.order.length} câu sai trong bộ: ${SETS[state.sourceSet].name}.`:""}
function render(){if(!state.order.length)state.order=baseOrder(state.activeSet);updateMetrics();renderToggles();renderMap();renderGlossary();renderQuestion();renderBanner()}
function showQuiz(){$("quizCard").style.display="block";$("results").style.display="none"} function showResults(){$("quizCard").style.display="none";$("results").style.display="block";updateMetrics();const c=correctCount(),t=state.order.length,p=t?c/t:0;$("finalScore").textContent=`${c}/${t}`;$("finalTitle").textContent=p>=.9?"Rất ổn.":p>=.7?"Ổn, còn vài câu cần luyện.":p>=.5?"Cần học lại keyword.":"Nên học lại từng câu.";$("finalMsg").textContent=`Bộ vừa làm: ${state.isRetry?"Câu sai của ":""}${SETS[state.sourceSet].name}.`;const r=$("reviewList");r.innerHTML="";state.order.forEach((idx,pos)=>{const item=QUESTIONS[idx], chosen=state.answers[idx]||"-", ok=chosen===item.answer;const row=document.createElement("button");row.className=`row ${ok?"correct":"wrong"}`;row.innerHTML=`<strong>Câu ${pos+1}</strong><span>${item.title}</span><span style="color:${ok?"var(--green)":"var(--red)"};font-weight:900">Bạn: ${chosen} · Đúng: ${item.answer}</span>`;row.onclick=()=>{state.current=pos;showQuiz();render()};r.appendChild(row)})}
function setStudyMode(){state.showQuestionVi=state.showOptionVi=state.showVocab=state.showExplain=true;toast("Đã bật chế độ học.");render()} function setExamMode(){state.showQuestionVi=state.showOptionVi=state.showVocab=state.showExplain=false;toast("Đã bật chế độ thi.");render()}
function resetCurrentSet(){const base=baseOrder(state.sourceSet);clearAnswersForOrder(base);state.activeSet=state.sourceSet;state.order=base;state.current=0;state.isRetry=false;$("setSelect").value=state.sourceSet;showQuiz();render();toast(`Đã làm lại bộ: ${SETS[state.sourceSet].name}.`)}
$("setSelect").onchange=e=>setOrder(e.target.value,false);$("allBtn").onclick=()=>setOrder("all",false);$("startBtn").onclick=()=>document.querySelector(".main").scrollIntoView({behavior:"smooth",block:"start"});$("learnBtn").onclick=setStudyMode;$("examBtn").onclick=setExamMode;$("themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=state.theme;localStorage.setItem("aPlusTheme",state.theme)};$("shuffleBtn").onclick=()=>{state.order=shuffle([...state.order]);state.current=0;showQuiz();render();toast(state.isRetry?"Đã trộn câu sai.":"Đã trộn bộ hiện tại.")};$("resetBtn").onclick=resetCurrentSet;$("restartBtn").onclick=resetCurrentSet;$("reviewAllBtn").onclick=()=>{state.current=0;showQuiz();render()};$("chooseAllResultBtn").onclick=()=>setOrder("all",false);$("backAllBtn").onclick=()=>setOrder("all",false);$("backSetBtn").onclick=()=>setOrder(state.sourceSet,false);$("retryWrongBtn").onclick=()=>{const wrong=state.order.filter(i=>state.answers[i]&&state.answers[i]!==QUESTIONS[i].answer);if(!wrong.length){toast("Không có câu sai để luyện lại.");return}state.sourceSet=state.activeSet;state.order=wrong;state.current=0;state.isRetry=true;setStudyMode();showQuiz();render();toast(`Đang luyện lại ${wrong.length} câu sai.`)};$("prevBtn").onclick=()=>{if(state.current>0){state.current--;render()}};$("nextBtn").onclick=()=>{if(state.current<state.order.length-1){state.current++;render()}else showResults()};$("glossarySearch").oninput=renderGlossary;[["toggleQuestionVi","showQuestionVi"],["toggleOptionVi","showOptionVi"],["toggleVocab","showVocab"],["toggleExplain","showExplain"]].forEach(([id,k])=>$(id).onclick=()=>{state[k]=!state[k];render()});
document.addEventListener("keydown",e=>{if(["INPUT","SELECT","TEXTAREA"].includes(document.activeElement.tagName))return;const key=e.key.toUpperCase();if(["A","B","C","D"].includes(key)&&!state.answers[qIndex()]){state.answers[qIndex()]=key;toast(key===q().answer?"Chính xác.":`Sai. Đáp án đúng là ${q().answer}.`);render()}if(e.key==="ArrowRight")$("nextBtn").click();if(e.key==="ArrowLeft")$("prevBtn").click();if(e.key.toLowerCase()==="t")$("toggleQuestionVi").click();if(e.key.toLowerCase()==="v")$("toggleVocab").click();if(e.key.toLowerCase()==="e")$("toggleExplain").click()});
setOrder("laptop",false);
